services:
  # Backend Service
  - type: web
    name: life-makers-dashboard-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: AZURE_CLIENT_ID
        sync: false
      - key: AZURE_CLIENT_SECRET
        sync: false
      - key: AZURE_TENANT_ID
        sync: false
      - key: SHAREPOINT_SITE_URL
        sync: false
      - key: EXCEL_FILE_PATH
        sync: false

  # Frontend Service
  - type: web
    name: life-makers-dashboard-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: REACT_APP_API_URL
        value: https://life-makers-dashboard-backend.onrender.com 